on:
  push:
    tags:        
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist
      - name: Zip file
        run: zip -r dist.zip dist/
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist.zip"
      - name: Publish to webstore
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: dist.zip
          extension-id: joipfehcpdlkelfihnodfepobadfgpke
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
